title: Raj Movva
url: "rmovva.github.io"
baseurl: ""

markdown: kramdown
remote_theme: ankitsultana/researcher@gem
# ins_logo: "./bits-logo.png"

# tracking_id: UA-69243698-4

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Webpage theme by Ankit Sultana."

favicon: true
favicon_location: "images/favicon.ico"

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "about"
    link: "/"
  - name: "publications"
    link: "/research"
  # - name: "blog"
  #   link: "/blog"
  - name: "cv"
    link: "/cv.pdf
